id: I057D0799
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T09:16:57+00:00'
last_modified: '2022-06-09T04:58:45.171532+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17540
  title: སྐལ་ལྡན་རྒྱ་མཚོའི་སྐྱེས་རབས་སྣང་བའི་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    50E4:
      image_group_id: I8LS17549
      title: ''
      total_pages: 352
      order: 1
      base_file: 50E4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
